### ISSUE TITLE
aftet each HA restart , I need to create new HUB to get it to work 

### ISSUE THREAD

**Issue by samimasad** [arjenbos/ha-postnl#28]
for every restart of HA , the integration show this issue
![image](https://github.com/user-attachments/assets/0355c780-2fbd-4b85-ae77-117498e3854e)

the only way is to delete that instant and create new one "it authinticate again through browser"
![image](https://github.com/user-attachments/assets/9285cca8-82ec-4e12-b180-b860f7a16ccd)

error found in the log : 
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 8:29:46 AM (1 occurrences)
Last logged: 8:29:46 AM

Error setting up entry xxxxxxxx for postnl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/postnl/__init__.py", line 77, in async_setup_entry
    entity_new_unique_id = userinfo.get('account_id') + "_" + unique_id_parts[1]
                                                              ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
great integration by the way

**Comment by arjenbos** [comment]
Could you please enable the debugging and share the log? **Please remove any privacy related information.**

I can fix the error (adding a default), but it will not solve the problem.

**Comment by arjenbos** [comment]
Additional question, did you rename the entities in the past?

**Comment by samimasad** [comment]
here is the log 
[home-assistant_postnl_2024-12-11T07-58-03.981Z.log](https://github.com/user-attachments/files/18091587/home-assistant_postnl_2024-12-11T07-58-03.981Z.log)
as for renaming , a release ago , it kept increamenting the sensor name so I was deleteing the old one and rename the new ones to the right name to get my automation to work

**Comment by arjenbos** [comment]
@samimasad I removed your comment, because the log contained personal information. I downloaded the log, and removed it. Because you mentioned that you renamed the entities. That's the reason why you see the error.

Could you please share the names of your entities? I will try to reproduce it on my test env.

**Comment by samimasad** [comment]
![image](https://github.com/user-attachments/assets/039fd33a-9491-45aa-8940-928549dfbf25)

**Comment by arjenbos** [comment]
I released a new version, should be fixed now.

**Comment by samimasad** [comment]
sorry to re-open , but i still have this issue , after each restart I have to readd
